1-uagents/finance/company-overview-agent/.avctl/config.toml, 1-uagents/finance/company-ticker-resolver-agent/.avctl/config.toml, 1-uagents/finance/finance-q&a-agent/.avctl/config.toml, 1-uagents/finance/financial-news-sentiment-agent/.avctl/config.toml, 1-uagents/finance/finbert-financial-sentiment-agent/.avctl/config.toml, 1-uagents/finance/stock-price-agent/.avctl/config.toml, 1-uagents/finance/technical-analysis-agent/.avctl/config.toml, 1-uagents/geo/geoapify-car-park-locator-agent/.avctl/config.toml, 1-uagents/geo/google-api-geolocation-agent/.avctl/config.toml, 1-uagents/geo/google-maps-places-agent/.avctl/config.toml, 1-uagents/geo/open-charge-map-agent/.avctl/config.toml, 1-uagents/geo/opencage-geolocation-agent/.avctl/config.toml, 1-uagents/knowledge-base/claude.ai-agent/.avctl/config.toml, 1-uagents/knowledge-base/google-gemini-agent/.avctl/config.toml, 1-uagents/knowledge-base/openai-agent/.avctl/config.toml, 1-uagents/search/tavily-search-agent/.avctl/config.toml, 1-uagents/travel/flights-retriever-agent/.avctl/config.toml, 1-uagents/utility/average-agent/.avctl/config.toml, 1-uagents/utility/openAI-translator-agent/.avctl/config.toml, 1-uagents/utility/weather-agent/.avctl/config.toml, 1-uagents/utility/website-scraper-agent/.avctl/config.toml, 1-uagents/utility/website-validation-agent/.avctl/config.toml
Add avctl deployment configs to agents
=> Add avctl deployment configs to agents

5-documentation/guides/agents/intermediate/mailbox/mailbox_agent_updated.py, 5-documentation/guides/agents/intermediate/mailbox/test_agent.py, 5-documentation/guides/fetch-network/cosmpy/use-cases/oracles/aerial_oracle_client.py, 5-documentation/guides/quickstart-with/CrewAI/creating-an-agent-with-crewai/crewai_agent_1.py, 5-documentation/guides/quickstart-with/CrewAI/creating-an-agent-with-crewai/crewai_agent_2.py
_Fixes examples code in repo._
=> fix: examples in repo

5-documentation/guides/agents/advanced/agents-async-loops/external_loop_attach.py, 5-documentation/guides/agents/advanced/agents-async-loops/external_loop_run.py, 5-documentation/guides/agents/advanced/message-verification/message_verification.py, 5-documentation/guides/agents/getting-started/create-a-uagent/first_agent.py, 5-documentation/guides/agents/getting-started/getting-uagent-address/fetch_address.py, 5-documentation/guides/agents/getting-started/getting-uagent-address/my_agent.py, 5-documentation/guides/agents/getting-started/getting-uagent-address/uagent_address.py, 5-documentation/guides/agents/intermediate/agent-types/mailbox_agent.py, 5-documentation/guides/agents/intermediate/communicating-with-other-agents/agent_communication.py, 5-documentation/guides/agents/intermediate/handlers/interval-task.py, 5-documentation/guides/agents/intermediate/hosted-agent/storage_agent_example.py, 5-documentation/guides/agents/intermediate/rest-endpoints/agent.py, 5-documentation/guides/agents/intermediate/send-tokens/sending_tokens.py, 5-documentation/guides/agents/intermediate/storage-function/storage.py, 5-documentation/guides/agents/quickstart/hosted/ReceiverAgent.py, 5-documentation/guides/agents/quickstart/local/interval_task.py
_[describe the changes here...]_
_[1043](https://github.com/fetchai/docs/issues/1043)_
=> fix: adds port and endpoints params in code

5-documentation/guides/agents/intermediate/langchain-rag-agent/README.md
=> feat: add README for langchain rag

5-documentation/guides/agents/intermediate/handlers/broadcast.py
_[describe the changes here...]_
=> fix: minor changes in broadcast code

1-uagents/examples/intermediate/agents-cleaning-demo/protocols/cleaning/__init__.py, 5-documentation/guides/agentverse/agentverse-functions/registering-agent-coin-toss/agent.py, 5-documentation/guides/agentverse/creating-agentverse-agents/simple-dice-roll-agent/agent.py
=> fix: multiple fixes in code snippets

4-community/MakeTrip_PICT_Codesnap/README.md
Corrected a typo in the Contributors section:
- Changed `Contibutors` to `Contributors`.
---
This PR is ready for review. 😊
=> Minor typo README.md

4-community/github_contributions/README.md
**Typo fix in README.md**
This pull request addresses a typo in the `README.md` file. The word **"sensative"** has been corrected to **"sensitive"**.
- Corrected the spelling of "sensative" to "sensitive" in the `README.md` file.
=> Typo fix README.md

.github/workflows/deploy-agents.yaml
=> fix(deployment): git add filter

.github/workflows/deploy-agents.yaml
_[describe the changes here...]_
=> fix(deployment): add deployment file to paths filter

.github/workflows/deploy-agents.yaml
Fix deployment script. It was failing before because the `main` branch is protected against pushes.
=> fix(deployment): create PR instead of pushing directly to main

1-uagents/utility/post-extractor-agent/agent.py
Add health check protocol to post extractor agent.
=> chore: add health check proto to post extractor agent

1-uagents/finance/finbert-financial-sentiment-agent/.avctl/config.toml, 1-uagents/geo/geoapify-car-park-locator-agent/.avctl/config.toml
_[describe the changes here...]_
=> chore: remove config for deleted agents

1-uagents/finance/company-overview-agent/README.md, 1-uagents/finance/company-ticker-resolver-agent/README.md, 1-uagents/finance/finance-q&a-agent/README.md, 1-uagents/finance/financial-news-sentiment-agent/README.md, 1-uagents/finance/finbert-financial-sentiment-agent/README.md, 1-uagents/finance/stock-price-agent/README.md, 1-uagents/finance/technical-analysis-agent/README.md, 1-uagents/geo/geoapify-car-park-locator-agent/README.md, 1-uagents/geo/google-api-geolocation-agent/README.md, 1-uagents/geo/google-maps-places-agent/README.md, 1-uagents/geo/open-charge-map-agent/README.md, 1-uagents/geo/opencage-geolocation-agent/README.md, 1-uagents/knowledge-base/claude.ai-agent/README.md, 1-uagents/knowledge-base/google-gemini-agent/README.md, 1-uagents/knowledge-base/openai-agent/README.md, 1-uagents/search/tavily-search-agent/README.md, 1-uagents/travel/flights-retriever-agent/README.md, 1-uagents/utility/average-agent/README.md, 1-uagents/utility/github-organisation-agent/README.md, 1-uagents/utility/github-pull-requests-agent/README.md, 1-uagents/utility/github-repositories-agent/README.md, 1-uagents/utility/grammar-agent/README.md, 1-uagents/utility/openAI-translator-agent/README.md, 1-uagents/utility/post-extractor-agent/README.md, 1-uagents/utility/weather-agent/README.md, 1-uagents/utility/website-scraper-agent/README.md
The format for including the agent address needs to be updated.
=> fix: deployed agent address template format

scripts/deploy-all-agents.sh
Uncomment the printing to secrets file
=> fix: uncomment print to secrets file

.github/workflows/deploy-agents.yaml, 1-uagents/geo/open-charge-map-agent/.avctl/config.toml, 1-uagents/knowledge-base/google-gemini-agent/.avctl/config.toml, 1-uagents/travel/flights-retriever-agent/.avctl/config.toml, 1-uagents/utility/github-organisation-agent/.avctl/config.toml, 1-uagents/utility/grammar-agent/.avctl/config.toml, scripts/deploy-all-agents.sh
- Add reddit credential
- Exclude website validatation from deployment script (this agent is deployed on the cluster)
- Correct some agent addresses that were out of sync
=> chore: add reddit credentials and correct agent addresses

1-uagents/examples_existing/04-storage/main.py, 1-uagents/examples_existing/06-send-tokens/main.py, 1-uagents/examples_existing/09-booking-protocol-demo/query.py, 1-uagents/examples_existing/20-send-and-receive/main.py
Sync examples from uAgent repo
=> chore: sync examples

scripts/deploy-all-agents.sh
=> fix: deployment script

scripts/deploy-all-agents.sh
Update the deployment script to deploy the agents to mainnet rather than testnet.
=> feat: switch deployed agents to mainnet

scripts/deploy-all-agents.sh
Reverts fetchai/uAgent-Examples#70
=> Revert "feat: switch deployed agents to mainnet"
